# Generated by Django 4.1.1 on 2022-09-07 04:04
from random import uniform

from django.db import migrations


def populate_students(apps, schema_editor):
    """Populates the database with test students."""
    Student = apps.get_model('django_primer', 'Student')
    
    students = [
        Student(name='Иванов', surname='Иван', email='ivanov.ivan@iivan.com'),
        Student(name='Иванов', surname='Ибрагим', email='ivanov.ibrahim@iivan.com'),
        Student(name='Петрова', surname='Екатерина', email='petrova.kate@pkate.com'),
    ]
    
    # Bulk create students
    Student.objects.bulk_create(students)


def populate_subjects(apps, schema_editor):
    """Populates the database with test subjects."""
    Subject = apps.get_model('django_primer', 'Subject')
    
    subjects = [
        Subject(name='ТиМП'),
        Subject(name='ЭиС'),
        Subject(name='Философия'),
        Subject(name='Иностранный язык'),
        Subject(name='Физическая культура'),
    ]
    
    # Bulk create subjects
    Subject.objects.bulk_create(subjects)


def populate_scores(apps, schema_editor):
    """Populates the database with test scores."""
    Student = apps.get_model('django_primer', 'Student')
    Subject = apps.get_model('django_primer', 'Subject')
    Score = apps.get_model('django_primer', 'Score')
    
    # Get all students and subjects
    students = Student.objects.all()
    subjects = Subject.objects.all()
    
    # Generate scores for each student and subject pair
    scores = [
        Score(student=student, subject=subject, value=uniform(0, 5))
        for student in students
        for subject in subjects
    ]
    
    # Bulk create scores
    Score.objects.bulk_create(scores)


def populate_test_data(apps, schema_editor):
    """Populates the database with test data."""
    populate_students(apps, schema_editor)
    populate_subjects(apps, schema_editor)
    populate_scores(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('django_primer', '0003_score'),
    ]

    operations = [
        migrations.RunPython(populate_test_data),
    ]
